/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.warehouse_smart.system;

/**
 *
 * @author cvdev
 */
import java.awt.BasicStroke;
import java.awt.BorderLayout;
import util.FontLoader;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.block.BlockBorder;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;
import com.formdev.flatlaf.FlatDarculaLaf;
import component.LocationPanel;
import component.ProductPanel;
import component.HistoryPanel;
import component.ReportsPanel;
        


import javax.swing.*;
import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Dashboard extends javax.swing.JFrame {
   private SalesTracker tracker;  
   private final int INITIAL_STOCK = 1015;
   private int mouseX, mouseY;
   private ProductPanel productPanel;
   private LocationPanel locationPanel;
   private HistoryPanel historyPanel;
   private ReportsPanel reportsPanel;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
          tracker = new SalesTracker();
        dashboardPanel1.updateChart();
        historyPanel = new HistoryPanel();
        jPanel17.add(historyPanel, "History");
         jPanel17.add(dashboardPanel1, "Dashboard");
         productPanel = new ProductPanel(dashboardPanel1, historyPanel);
         productPanel.setOpaque(false);
         jPanel17.add(productPanel, "Product");
         locationPanel = new LocationPanel();
         locationPanel.setOpaque(false);
         jPanel17.add(locationPanel, "Location");
         
         reportsPanel = new ReportsPanel();
         jPanel17.add(reportsPanel, "Reports");
   CardLayout cl = (CardLayout) jPanel17.getLayout();
    cl.show(jPanel17, "Dashboard");
    
    setTime();
    
    }
    



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        simulateBtn = new javax.swing.JButton();
        jPanel12 = new RoundPanel(20);
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel14 = new RoundPanel(20);
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel15 = new RoundPanel(20);
        jLabelProduct = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel16 = new RoundPanel(20);
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtTime = new javax.swing.JLabel();
        jTxtDate = new javax.swing.JLabel();
        jPanel18 = new RoundPanel(20);
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        dashboardPanel1 = new component.DashboardPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(Color.decode("#1A1A1A"));
        setIconImage(new ImageIcon(getClass().getResource("/logoIcon.png")).getImage()
        );
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBorder(new RoundedPanel(
            20,
            new Color(108, 74, 181),
            2
        ));
        jPanel1.setBackground(Color.decode("#1A1A1A"));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 573));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jPanel2.setBorder(new RoundedPanel(
            20,
            new Color(33, 33, 33),
            0
        ));
        jPanel2.setBackground(Color.decode("#212121"));
        jPanel2.setPreferredSize(new java.awt.Dimension(174, 578));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo resize.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        simulateBtn.setText("Simulate");
        simulateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(simulateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jPanel12.setBackground(Color.decode("#5541CB"));
        jPanel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });

        Font dmSans = FontLoader.loadFont("resources/fonts/DMSans_24pt-Medium.ttf", 24f);
        jLabel2.setFont(dmSans);
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(Color.decode("#D6D6D6"));
        jLabel2.setText("Home");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vector (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(11, 11, 11))
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 174, 40));

        jPanel14.setBackground(Color.decode("#212121"));
        jPanel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });

        jLabel3.setFont(dmSans);
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(Color.decode("#D6D6D6"));
        jLabel3.setText("Locations");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vector-2 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 174, 40));

        jPanel15.setBackground(Color.decode("#212121"));
        jPanel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });

        jLabelProduct.setFont(dmSans);
        jLabelProduct.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabelProduct.setForeground(Color.decode("#D6D6D6"));
        jLabelProduct.setText("Products");
        jLabelProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProductMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vector-3 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabelProduct)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelProduct)
                    .addComponent(jLabel10))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 174, 40));

        jPanel16.setBackground(Color.decode("#212121"));
        jPanel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16MouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vector-1 (1).png"))); // NOI18N

        jLabel5.setFont(dmSans);
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(Color.decode("#D6D6D6"));
        jLabel5.setText("Reports");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel23))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 174, 40));

        Font roboto1 = FontLoader.loadFont("resources/fonts/Roboto-ExtraBold.ttf", 20f);
        jTxtTime.setFont(roboto1);
        jTxtTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtTime.setText("jLabel4");
        jPanel2.add(jTxtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 180, -1));

        Font roboto3 = FontLoader.loadFont("resources/fonts/Roboto-ExtraBold.ttf", 15f);
        jTxtDate.setFont(roboto3);
        jTxtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtDate.setText("jLabel4");
        jPanel2.add(jTxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 180, -1));

        jPanel18.setBackground(Color.decode("#212121"));
        jPanel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18MouseClicked(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/History Icon.png"))); // NOI18N

        jLabel5.setFont(dmSans);
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(Color.decode("#D6D6D6"));
        jLabel6.setText("History");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel24))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 174, 40));

        jPanel17.setBackground(Color.decode("#1A1A1A"));
        jPanel17.setOpaque(false);
        jPanel17.setPreferredSize(new java.awt.Dimension(842, 567));
        jPanel17.setLayout(new java.awt.CardLayout());

        dashboardPanel1.setOpaque(false);
        jPanel17.add(dashboardPanel1, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simulateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateBtnActionPerformed
        dashboardPanel1.recordSale("Manila", "AquaThirst Colorwave", 30); 
        dashboardPanel1.recordSale("Manila", "AquaThirst Dream", 50); 
        dashboardPanel1.recordSale("Pasay", "Cylinder Collections", 50);
     dashboardPanel1.updateChart();
        
    
    }//GEN-LAST:event_simulateBtnActionPerformed

    private void jLabelProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProductMouseClicked
        
    }//GEN-LAST:event_jLabelProductMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         
    }//GEN-LAST:event_formMousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
         mouseX = evt.getX();
         mouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        CardLayout cl = (CardLayout) jPanel17.getLayout();
        cl.show(jPanel17, "Product");
        jPanel15.setBackground(Color.decode("#5541CB"));
        jPanel12.setBackground(Color.decode("#212121"));
        jPanel14.setBackground(Color.decode("#212121"));
        jPanel16.setBackground(Color.decode("#212121"));
        jPanel18.setBackground(Color.decode("#212121"));

    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        CardLayout cl = (CardLayout) jPanel17.getLayout();
        cl.show(jPanel17, "Dashboard");
        jPanel12.setBackground(Color.decode("#5541CB"));
        jPanel15.setBackground(Color.decode("#212121"));
        jPanel14.setBackground(Color.decode("#212121"));
        jPanel16.setBackground(Color.decode("#212121"));
        jPanel18.setBackground(Color.decode("#212121"));

    }//GEN-LAST:event_jPanel12MouseClicked
    
    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        CardLayout cl = (CardLayout) jPanel17.getLayout();
        cl.show(jPanel17, "Location");
        jPanel14.setBackground(Color.decode("#5541CB"));
        jPanel15.setBackground(Color.decode("#212121"));
        jPanel12.setBackground(Color.decode("#212121"));
        jPanel16.setBackground(Color.decode("#212121"));
        jPanel18.setBackground(Color.decode("#212121"));
        
    }//GEN-LAST:event_jPanel14MouseClicked

    private void jPanel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseClicked
    CardLayout cl = (CardLayout) jPanel17.getLayout();
    cl.show(jPanel17, "Reports");
    jPanel16.setBackground(Color.decode("#5541CB"));
    jPanel15.setBackground(Color.decode("#212121"));
    jPanel12.setBackground(Color.decode("#212121"));
    jPanel14.setBackground(Color.decode("#212121"));
    jPanel18.setBackground(Color.decode("#212121"));
      
    }//GEN-LAST:event_jPanel16MouseClicked

    private void jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseClicked
    CardLayout cl = (CardLayout) jPanel17.getLayout();
    cl.show(jPanel17, "History");
    jPanel18.setBackground(Color.decode("#5541CB"));
    jPanel16.setBackground(Color.decode("#212121"));
    jPanel15.setBackground(Color.decode("#212121"));
    jPanel12.setBackground(Color.decode("#212121"));
    jPanel14.setBackground(Color.decode("#212121"));
    
    }//GEN-LAST:event_jPanel18MouseClicked
    public void setTime() {
        new Thread(new Runnable() {
            @Override
            @SuppressWarnings("empty-statement")
            public void run() {
                while(true) {
                    try {
                        Thread.sleep(1000);
                    }
                    catch(InterruptedException ex) {
                        Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                    }
                  Date date = new Date();
                  SimpleDateFormat tf = new SimpleDateFormat("h:mm:ssaa");
                  SimpleDateFormat df = new SimpleDateFormat("EEEE, dd-MM-yyyy");
                  String time = tf.format(date);
                  String[] timeParts = time.split(" ");
                          
                  SwingUtilities.invokeLater(() -> {
                    if(timeParts.length >= 2) {
                        jTxtTime.setText(timeParts[0] + " " + timeParts[1]);
                    }
                    else {
                        jTxtTime.setText(time);
                    }
                    jTxtDate.setText(df.format(date));
                
                });
            }
        }
    }).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatDarculaLaf.setup();
                new Dashboard().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.DashboardPanel dashboardPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelProduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jTxtDate;
    private javax.swing.JLabel jTxtTime;
    private javax.swing.JButton simulateBtn;
    // End of variables declaration//GEN-END:variables

   
}
